wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 128
hidden_dim:
  value: 128
lr:
  value: 0.0001
max_seq_len:
  value: 10
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 7
patience:
  value: 10
