wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 16
hidden_dim:
  value: 16
lr:
  value: 0.01
max_seq_len:
  value: 38
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 9
patience:
  value: 10
