wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 512
hidden_dim:
  value: 512
lr:
  value: 0.1
max_seq_len:
  value: 39
model:
  value: lstm
n_epochs:
  value: 100
n_layers:
  value: 2
patience:
  value: 10
