wandb_version: 1

batch_size:
  value: 256
embed_dim:
  value: 128
hidden_dim:
  value: 64
lr:
  value: 0.0001
max_seq_len:
  value: 28
model:
  value: lstm
n_epochs:
  value: 198
n_layers:
  value: 4
patience:
  value: 25
