wandb_version: 1

batch_size:
  value: 256
embed_dim:
  value: 16
hidden_dim:
  value: 128
lr:
  value: 0.0001
max_seq_len:
  value: 37
model:
  value: lstm
n_epochs:
  value: 395
n_layers:
  value: 10
patience:
  value: 25
