wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 16
hidden_dim:
  value: 64
lr:
  value: 1.0e-05
max_seq_len:
  value: 16
model:
  value: lstm
n_epochs:
  value: 343
n_layers:
  value: 5
patience:
  value: 25
