wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.4
embed_dim:
  value: 32
hidden_dim:
  value: 256
lr:
  value: 0.01
max_seq_len:
  value: 39
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 6
patience:
  value: 10
