wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.1
embed_dim:
  value: 256
hidden_dim:
  value: 64
lr:
  value: 0.1
max_seq_len:
  value: 28
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 9
patience:
  value: 10
