wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1669342036.953544
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.15
      5: 0.13.5
      6: 4.24.0
      8:
      - 5
asset_dir:
  desc: null
  value: asset/
batch_size:
  desc: null
  value: 64
cate_cols:
  desc: null
  value:
  - assessmentItemID
  - testId
  - KnowledgeTag
  - assessmentItemID_last
  - testId_first
  - testId_last
clip_grad:
  desc: null
  value: 10
cont_cols:
  desc: null
  value:
  - elapsed
data_dir:
  desc: null
  value: /opt/ml/input/data/
device:
  desc: null
  value: cuda
drop_out:
  desc: null
  value: 0.2
embed_dim:
  desc: null
  value: 64
file_name:
  desc: null
  value: train_feature_engineering.csv
hidden_dim:
  desc: null
  value: 64
log_steps:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
max_seq_len:
  desc: null
  value: 20
model:
  desc: null
  value: lstmattn
model_dir:
  desc: null
  value: models/
model_name:
  desc: null
  value: model_lstmattn_without_cont.pt
n_epochs:
  desc: null
  value: 20
n_heads:
  desc: null
  value: 2
n_layers:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 1
offset:
  desc: null
  value: 12124
optimizer:
  desc: null
  value: adam
output_dir:
  desc: null
  value: output/
output_file_name:
  desc: null
  value: submission.csv
patience:
  desc: null
  value: 5
scheduler:
  desc: null
  value: plateau
seed:
  desc: null
  value: 42
test_file_name:
  desc: null
  value: test_feature_engineering.csv
