wandb_version: 1

batch_size:
  value: 256
embed_dim:
  value: 64
hidden_dim:
  value: 256
lr:
  value: 0.0001
max_seq_len:
  value: 8
model:
  value: bert
n_epochs:
  value: 327
n_heads:
  value: 8
n_layers:
  value: 7
patience:
  value: 25
