wandb_version: 1

batch_size:
  value: 128
embed_dim:
  value: 64
hidden_dim:
  value: 32
lr:
  value: 0.0001
max_seq_len:
  value: 8
model:
  value: bert
n_epochs:
  value: 196
n_heads:
  value: 10
n_layers:
  value: 2
patience:
  value: 25
