wandb_version: 1

batch_size:
  value: 256
embed_dim:
  value: 128
hidden_dim:
  value: 512
lr:
  value: 0.1
max_seq_len:
  value: 44
model:
  value: bert
n_epochs:
  value: 412
n_heads:
  value: 3
n_layers:
  value: 9
patience:
  value: 25
