wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 256
hidden_dim:
  value: 16
lr:
  value: 0.001
max_seq_len:
  value: 27
model:
  value: bert
n_epochs:
  value: 275
n_heads:
  value: 7
n_layers:
  value: 8
patience:
  value: 25
