wandb_version: 1

batch_size:
  value: 218
dropout:
  value: 0.4
embed_dim:
  value: 84
hidden_dim:
  value: 118
lr:
  value: 0.03509494395271439
max_seq_len:
  value: 5
n_epochs:
  value: 14
n_heads:
  value: 4
n_layers:
  value: 1
optimizer:
  value: adam
scheduler:
  value: linear_warmup
