wandb_version: 1

batch_size:
  value: 82
dropout:
  value: 0.3
embed_dim:
  value: 80
hidden_dim:
  value: 94
lr:
  value: 0.004763220110182032
max_seq_len:
  value: 47
n_epochs:
  value: 12
n_heads:
  value: 3
n_layers:
  value: 3
optimizer:
  value: adam
scheduler:
  value: linear_warmup
