wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.3
embed_dim:
  value: 64
hidden_dim:
  value: 16
lr:
  value: 0.01
max_seq_len:
  value: 7
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: adam
patience:
  value: 5
scheduler:
  value: plateau
