wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 64
hidden_dim:
  value: 32
lr:
  value: 0.0001
max_seq_len:
  value: 6
model:
  value: lstm
n_epochs:
  value: 100
n_layers:
  value: 1
patience:
  value: 10
