wandb_version: 1

batch_size:
  value: 256
embed_dim:
  value: 16
hidden_dim:
  value: 512
lr:
  value: 1.0e-05
max_seq_len:
  value: 5
model:
  value: lstm
n_epochs:
  value: 100
n_layers:
  value: 1
patience:
  value: 10
