wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 16
hidden_dim:
  value: 256
lr:
  value: 0.001
max_seq_len:
  value: 46
model:
  value: lstm
n_epochs:
  value: 100
n_layers:
  value: 1
patience:
  value: 10
