wandb_version: 1

batch_size:
  value: 128
embed_dim:
  value: 512
hidden_dim:
  value: 256
lr:
  value: 0.001
max_seq_len:
  value: 7
model:
  value: lstm
n_epochs:
  value: 100
n_layers:
  value: 1
patience:
  value: 10
