wandb_version: 1

batch_size:
  value: 95
dropout:
  value: 0.4
embed_dim:
  value: 81
hidden_dim:
  value: 43
lr:
  value: 0.07317967799931231
max_seq_len:
  value: 67
n_epochs:
  value: 21
n_layers:
  value: 1
optimizer:
  value: adamW
scheduler:
  value: plateau
