wandb_version: 1

batch_size:
  value: 153
dropout:
  value: 0.3
embed_dim:
  value: 90
hidden_dim:
  value: 49
lr:
  value: 0.06635074244414718
max_seq_len:
  value: 55
n_epochs:
  value: 38
n_layers:
  value: 4
optimizer:
  value: adamW
scheduler:
  value: plateau
