wandb_version: 1

batch_size:
  value: 256
embed_dim:
  value: 64
hidden_dim:
  value: 16
lr:
  value: 0.001
max_seq_len:
  value: 18
model:
  value: bert
n_epochs:
  value: 257
n_heads:
  value: 1
n_layers:
  value: 2
patience:
  value: 25
