wandb_version: 1

batch_size:
  value: 115
dropout:
  value: 0.4
embed_dim:
  value: 104
hidden_dim:
  value: 86
lr:
  value: 0.04592146616527342
max_seq_len:
  value: 20
n_epochs:
  value: 34
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: adam
scheduler:
  value: linear_warmup
