wandb_version: 1

batch_size:
  value: 256
dropout:
  value: 0.4
embed_dim:
  value: 64
hidden_dim:
  value: 64
lr:
  value: 0.02864280432391064
max_seq_len:
  value: 25
n_epochs:
  value: 56
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: adam
scheduler:
  value: linear_warmup
