wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4
embed_dim:
  value: 128
hidden_dim:
  value: 128
lr:
  value: 0.07141050909717751
max_seq_len:
  value: 6
n_epochs:
  value: 72
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: adam
scheduler:
  value: linear_warmup
