wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1669700530.31474
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 23
      4: 3.8.15
      5: 0.13.5
      6: 4.24.0
      8:
      - 5
batch_size:
  desc: null
  value: 52
dropout:
  desc: null
  value: 0.4
embed_dim:
  desc: null
  value: 56
hidden_dim:
  desc: null
  value: 67
lr:
  desc: null
  value: 0.02463409684457335
max_seq_len:
  desc: null
  value: 30
n_epochs:
  desc: null
  value: 26
n_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: adamW
scheduler:
  desc: null
  value: plateau
