wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.5
embed_dim:
  value: 64
hidden_dim:
  value: 32
lr:
  value: 0.01
max_seq_len:
  value: 41
model:
  value: lstmattn
n_epochs:
  value: 433
n_heads:
  value: 3
n_layers:
  value: 3
patience:
  value: 25
