wandb_version: 1

batch_size:
  value: 512
drop_out:
  value: 0.2
embed_dim:
  value: 32
hidden_dim:
  value: 512
lr:
  value: 0.1
max_seq_len:
  value: 46
model:
  value: lstmattn
n_epochs:
  value: 127
n_heads:
  value: 6
n_layers:
  value: 3
patience:
  value: 25
