wandb_version: 1

batch_size:
  value: 128
embed_dim:
  value: 512
hidden_dim:
  value: 256
lr:
  value: 0.1
max_seq_len:
  value: 21
model:
  value: lstm
n_epochs:
  value: 157
n_layers:
  value: 1
patience:
  value: 25
