wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.4
embed_dim:
  value: 128
hidden_dim:
  value: 128
lr:
  value: 0.1
max_seq_len:
  value: 24
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: adam
patience:
  value: 5
scheduler:
  value: plateau
