wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1669700514.508819
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.15
      5: 0.13.5
      6: 4.24.0
      8:
      - 5
batch_size:
  desc: null
  value: 152
dropout:
  desc: null
  value: 0.4
embed_dim:
  desc: null
  value: 246
hidden_dim:
  desc: null
  value: 84
lr:
  desc: null
  value: 0.08190588966860046
max_seq_len:
  desc: null
  value: 12
n_epochs:
  desc: null
  value: 89
n_layers:
  desc: null
  value: 5
optimizer:
  desc: null
  value: adam
scheduler:
  desc: null
  value: plateau
