wandb_version: 1

batch_size:
  value: 152
dropout:
  value: 0.4
embed_dim:
  value: 246
hidden_dim:
  value: 84
lr:
  value: 0.08190588966860046
max_seq_len:
  value: 12
n_epochs:
  value: 89
n_layers:
  value: 5
optimizer:
  value: adam
scheduler:
  value: plateau
