wandb_version: 1

batch_size:
  value: 52
dropout:
  value: 0.4
embed_dim:
  value: 56
hidden_dim:
  value: 67
lr:
  value: 0.02463409684457335
max_seq_len:
  value: 30
n_epochs:
  value: 26
n_layers:
  value: 3
optimizer:
  value: adamW
scheduler:
  value: plateau
