wandb_version: 1

batch_size:
  value: 41
dropout:
  value: 0.4
embed_dim:
  value: 57
hidden_dim:
  value: 135
lr:
  value: 0.04271540721525213
max_seq_len:
  value: 35
n_epochs:
  value: 14
n_layers:
  value: 4
optimizer:
  value: adam
scheduler:
  value: linear_warmup
