wandb_version: 1

batch_size:
  value: 150
dropout:
  value: 0.4
embed_dim:
  value: 91
hidden_dim:
  value: 100
lr:
  value: 0.09770554748016252
max_seq_len:
  value: 56
n_epochs:
  value: 46
n_layers:
  value: 1
optimizer:
  value: adamW
scheduler:
  value: linear_warmup
