wandb_version: 1

batch_size:
  value: 63
dropout:
  value: 0.4
embed_dim:
  value: 42
hidden_dim:
  value: 59
lr:
  value: 0.0002698488169006419
max_seq_len:
  value: 20
n_epochs:
  value: 25
n_layers:
  value: 4
optimizer:
  value: adamW
scheduler:
  value: plateau
