wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 32
hidden_dim:
  value: 16
lr:
  value: 0.001
max_seq_len:
  value: 18
model:
  value: lstm
n_epochs:
  value: 100
n_layers:
  value: 2
patience:
  value: 10
