wandb_version: 1

batch_size:
  value: 128
embed_dim:
  value: 64
hidden_dim:
  value: 512
lr:
  value: 0.1
max_seq_len:
  value: 37
model:
  value: lstm
n_epochs:
  value: 100
n_layers:
  value: 4
patience:
  value: 10
