wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 128
hidden_dim:
  value: 128
lr:
  value: 0.0001
max_seq_len:
  value: 46
model:
  value: lstm
n_epochs:
  value: 100
n_layers:
  value: 3
patience:
  value: 10
