wandb_version: 1

batch_size:
  value: 34
dropout:
  value: 0.4
embed_dim:
  value: 145
hidden_dim:
  value: 59
lr:
  value: 0.09354717667391094
max_seq_len:
  value: 26
n_epochs:
  value: 96
n_layers:
  value: 4
optimizer:
  value: adam
scheduler:
  value: plateau
