wandb_version: 1

batch_size:
  value: 133
dropout:
  value: 0.4
embed_dim:
  value: 112
hidden_dim:
  value: 37
lr:
  value: 0.047363998769373694
max_seq_len:
  value: 38
n_epochs:
  value: 43
n_layers:
  value: 5
optimizer:
  value: adam
scheduler:
  value: linear_warmup
