wandb_version: 1

batch_size:
  value: 187
dropout:
  value: 0.4
embed_dim:
  value: 38
hidden_dim:
  value: 45
lr:
  value: 0.03937338119174843
max_seq_len:
  value: 22
n_epochs:
  value: 42
n_layers:
  value: 4
optimizer:
  value: adam
scheduler:
  value: plateau
