wandb_version: 1

batch_size:
  value: 512
drop_out:
  value: 0.1
embed_dim:
  value: 128
hidden_dim:
  value: 256
lr:
  value: 0.01
max_seq_len:
  value: 6
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 5
patience:
  value: 10
