wandb_version: 1

batch_size:
  value: 256
drop_out:
  value: 0.2
embed_dim:
  value: 128
hidden_dim:
  value: 128
lr:
  value: 0.1
max_seq_len:
  value: 11
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 5
patience:
  value: 10
