wandb_version: 1

batch_size:
  value: 256
drop_out:
  value: 0.5
embed_dim:
  value: 64
hidden_dim:
  value: 128
lr:
  value: 0.0001
max_seq_len:
  value: 43
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 9
patience:
  value: 10
