wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.4
embed_dim:
  value: 256
hidden_dim:
  value: 256
lr:
  value: 0.09007934535980498
max_seq_len:
  value: 39
n_epochs:
  value: 88
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: adamW
scheduler:
  value: linear_warmup
