wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.3
embed_dim:
  value: 32
hidden_dim:
  value: 32
lr:
  value: 0.08003754071050564
max_seq_len:
  value: 40
n_epochs:
  value: 28
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: adam
scheduler:
  value: linear_warmup
