wandb_version: 1

batch_size:
  value: 64
drop_out:
  value: 0.2
embed_dim:
  value: 16
hidden_dim:
  value: 256
lr:
  value: 0.0001
max_seq_len:
  value: 22
model:
  value: lstmattn
n_epochs:
  value: 160
n_heads:
  value: 1
n_layers:
  value: 10
patience:
  value: 25
