wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 16
hidden_dim:
  value: 64
lr:
  value: 0.1
max_seq_len:
  value: 29
model:
  value: bert
n_epochs:
  value: 179
n_heads:
  value: 4
n_layers:
  value: 1
patience:
  value: 25
