wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 32
hidden_dim:
  value: 32
lr:
  value: 0.0001
max_seq_len:
  value: 47
model:
  value: bert
n_epochs:
  value: 398
n_heads:
  value: 4
n_layers:
  value: 7
patience:
  value: 25
