wandb_version: 1

batch_size:
  value: 256
drop_out:
  value: 0.2
embed_dim:
  value: 16
hidden_dim:
  value: 256
lr:
  value: 1.0e-05
max_seq_len:
  value: 7
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 3
patience:
  value: 10
