wandb_version: 1

batch_size:
  value: 512
drop_out:
  value: 0.2
embed_dim:
  value: 64
hidden_dim:
  value: 64
lr:
  value: 1.0e-05
max_seq_len:
  value: 6
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 1
patience:
  value: 10
