wandb_version: 1

batch_size:
  value: 64
drop_out:
  value: 0.4
embed_dim:
  value: 512
hidden_dim:
  value: 256
lr:
  value: 0.001
max_seq_len:
  value: 14
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 1
patience:
  value: 10
