wandb_version: 1

batch_size:
  value: 256
drop_out:
  value: 0.5
embed_dim:
  value: 512
hidden_dim:
  value: 512
lr:
  value: 0.001
max_seq_len:
  value: 6
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 3
patience:
  value: 10
