wandb_version: 1

batch_size:
  value: 64
drop_out:
  value: 0.4
embed_dim:
  value: 64
hidden_dim:
  value: 256
lr:
  value: 0.0001
max_seq_len:
  value: 11
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 1
patience:
  value: 10
