wandb_version: 1

batch_size:
  value: 256
drop_out:
  value: 0.1
embed_dim:
  value: 32
hidden_dim:
  value: 256
lr:
  value: 0.0001
max_seq_len:
  value: 6
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 4
patience:
  value: 10
