wandb_version: 1

batch_size:
  value: 512
drop_out:
  value: 0.1
embed_dim:
  value: 64
hidden_dim:
  value: 256
lr:
  value: 0.001
max_seq_len:
  value: 17
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 1
patience:
  value: 10
