wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.1
embed_dim:
  value: 16
hidden_dim:
  value: 512
lr:
  value: 1.0e-05
max_seq_len:
  value: 21
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 4
patience:
  value: 10
