wandb_version: 1

batch_size:
  value: 512
drop_out:
  value: 0.2
embed_dim:
  value: 256
hidden_dim:
  value: 512
lr:
  value: 0.1
max_seq_len:
  value: 30
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 2
patience:
  value: 10
