wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.1
embed_dim:
  value: 64
hidden_dim:
  value: 16
lr:
  value: 0.001
max_seq_len:
  value: 24
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 5
patience:
  value: 10
