wandb_version: 1

batch_size:
  value: 512
drop_out:
  value: 0.2
embed_dim:
  value: 32
hidden_dim:
  value: 256
lr:
  value: 1.0e-05
max_seq_len:
  value: 11
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 2
patience:
  value: 10
