wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.5
embed_dim:
  value: 16
hidden_dim:
  value: 512
lr:
  value: 0.001
max_seq_len:
  value: 5
model:
  value: lstmattn
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 7
patience:
  value: 10
