wandb_version: 1

batch_size:
  value: 88
dropout:
  value: 0.3
embed_dim:
  value: 33
hidden_dim:
  value: 166
lr:
  value: 0.01632990199125074
max_seq_len:
  value: 64
n_epochs:
  value: 36
n_layers:
  value: 3
optimizer:
  value: adam
scheduler:
  value: plateau
