wandb_version: 1

batch_size:
  value: 89
dropout:
  value: 0.3
embed_dim:
  value: 78
hidden_dim:
  value: 96
lr:
  value: 0.04795784017543823
max_seq_len:
  value: 89
n_epochs:
  value: 59
n_layers:
  value: 4
optimizer:
  value: adam
scheduler:
  value: linear_warmup
