wandb_version: 1

batch_size:
  value: 48
dropout:
  value: 0.3
embed_dim:
  value: 49
hidden_dim:
  value: 94
lr:
  value: 0.01503234656516752
max_seq_len:
  value: 27
n_epochs:
  value: 90
n_layers:
  value: 2
optimizer:
  value: adamW
scheduler:
  value: linear_warmup
