wandb_version: 1

batch_size:
  value: 256
dropout:
  value: 0.4
embed_dim:
  value: 256
hidden_dim:
  value: 256
lr:
  value: 0.01
max_seq_len:
  value: 33
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: adam
patience:
  value: 5
scheduler:
  value: plateau
