wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 128
hidden_dim:
  value: 32
lr:
  value: 0.1
max_seq_len:
  value: 43
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 9
patience:
  value: 10
