wandb_version: 1

batch_size:
  value: 128
embed_dim:
  value: 256
hidden_dim:
  value: 64
lr:
  value: 0.0001
max_seq_len:
  value: 43
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 3
patience:
  value: 10
