wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 16
hidden_dim:
  value: 64
lr:
  value: 0.0001
max_seq_len:
  value: 8
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 9
patience:
  value: 10
