wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 16
hidden_dim:
  value: 512
lr:
  value: 0.0001
max_seq_len:
  value: 10
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 10
patience:
  value: 10
