wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 32
hidden_dim:
  value: 32
lr:
  value: 0.01
max_seq_len:
  value: 10
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 3
patience:
  value: 10
