wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 32
hidden_dim:
  value: 128
lr:
  value: 0.0001
max_seq_len:
  value: 7
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 10
patience:
  value: 10
