wandb_version: 1

batch_size:
  value: 256
embed_dim:
  value: 16
hidden_dim:
  value: 256
lr:
  value: 0.0001
max_seq_len:
  value: 11
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 5
patience:
  value: 10
