wandb_version: 1

batch_size:
  value: 128
embed_dim:
  value: 32
hidden_dim:
  value: 256
lr:
  value: 1.0e-05
max_seq_len:
  value: 7
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 6
patience:
  value: 10
