wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 64
hidden_dim:
  value: 512
lr:
  value: 1.0e-05
max_seq_len:
  value: 6
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 8
patience:
  value: 10
