wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 512
hidden_dim:
  value: 256
lr:
  value: 0.01
max_seq_len:
  value: 5
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 10
patience:
  value: 10
