wandb_version: 1

batch_size:
  value: 512
embed_dim:
  value: 32
hidden_dim:
  value: 16
lr:
  value: 0.001
max_seq_len:
  value: 9
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 10
patience:
  value: 10
