wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 16
hidden_dim:
  value: 128
lr:
  value: 0.01
max_seq_len:
  value: 7
model:
  value: bert
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 2
patience:
  value: 10
