wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.2
embed_dim:
  value: 32
hidden_dim:
  value: 256
lr:
  value: 1.0e-05
max_seq_len:
  value: 43
model:
  value: lstmattn
n_epochs:
  value: 285
n_heads:
  value: 6
n_layers:
  value: 6
patience:
  value: 25
