wandb_version: 1

batch_size:
  value: 256
drop_out:
  value: 0.5
embed_dim:
  value: 64
hidden_dim:
  value: 16
lr:
  value: 0.1
max_seq_len:
  value: 20
model:
  value: lstmattn
n_epochs:
  value: 232
n_heads:
  value: 4
n_layers:
  value: 7
patience:
  value: 25
