wandb_version: 1

batch_size:
  value: 64
drop_out:
  value: 0.3
embed_dim:
  value: 128
hidden_dim:
  value: 128
lr:
  value: 0.01
max_seq_len:
  value: 10
model:
  value: lstmattn
n_epochs:
  value: 137
n_heads:
  value: 3
n_layers:
  value: 1
patience:
  value: 25
