wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 16
hidden_dim:
  value: 32
lr:
  value: 0.01
max_seq_len:
  value: 26
model:
  value: lstm
n_epochs:
  value: 171
n_layers:
  value: 2
patience:
  value: 25
