wandb_version: 1

batch_size:
  value: 64
embed_dim:
  value: 256
hidden_dim:
  value: 128
lr:
  value: 0.001
max_seq_len:
  value: 10
model:
  value: lstm
n_epochs:
  value: 222
n_layers:
  value: 8
patience:
  value: 25
