wandb_version: 1

batch_size:
  value: 256
embed_dim:
  value: 32
hidden_dim:
  value: 512
lr:
  value: 0.001
max_seq_len:
  value: 36
model:
  value: lstm
n_epochs:
  value: 116
n_layers:
  value: 1
patience:
  value: 25
