wandb_version: 1

batch_size:
  value: 512
drop_out:
  value: 0.5
embed_dim:
  value: 16
hidden_dim:
  value: 128
lr:
  value: 1.0e-05
max_seq_len:
  value: 14
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 2
n_layers:
  value: 1
patience:
  value: 10
