wandb_version: 1

batch_size:
  value: 256
drop_out:
  value: 0.1
embed_dim:
  value: 512
hidden_dim:
  value: 32
lr:
  value: 0.001
max_seq_len:
  value: 40
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 7
patience:
  value: 10
