wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.4
embed_dim:
  value: 16
hidden_dim:
  value: 32
lr:
  value: 0.0001
max_seq_len:
  value: 29
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 1
patience:
  value: 10
