wandb_version: 1

batch_size:
  value: 64
drop_out:
  value: 0.4
embed_dim:
  value: 32
hidden_dim:
  value: 32
lr:
  value: 0.0001
max_seq_len:
  value: 15
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 1
patience:
  value: 10
