wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.5
embed_dim:
  value: 16
hidden_dim:
  value: 16
lr:
  value: 0.01
max_seq_len:
  value: 23
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 1
patience:
  value: 10
