wandb_version: 1

batch_size:
  value: 512
drop_out:
  value: 0.4
embed_dim:
  value: 32
hidden_dim:
  value: 64
lr:
  value: 0.001
max_seq_len:
  value: 32
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 1
n_layers:
  value: 2
patience:
  value: 10
