wandb_version: 1

batch_size:
  value: 256
drop_out:
  value: 0.1
embed_dim:
  value: 32
hidden_dim:
  value: 512
lr:
  value: 1.0e-05
max_seq_len:
  value: 15
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 8
n_layers:
  value: 1
patience:
  value: 10
