wandb_version: 1

batch_size:
  value: 128
drop_out:
  value: 0.2
embed_dim:
  value: 64
hidden_dim:
  value: 512
lr:
  value: 0.0001
max_seq_len:
  value: 28
model:
  value: lastquery
n_epochs:
  value: 100
n_heads:
  value: 4
n_layers:
  value: 1
patience:
  value: 10
