wandb_version: 1

batch_size:
  value: 49
dropout:
  value: 0.3
embed_dim:
  value: 64
hidden_dim:
  value: 73
lr:
  value: 0.009362796151604114
max_seq_len:
  value: 56
n_epochs:
  value: 38
n_layers:
  value: 5
optimizer:
  value: adam
scheduler:
  value: plateau
