wandb_version: 1

batch_size:
  value: 85
dropout:
  value: 0.3
embed_dim:
  value: 57
hidden_dim:
  value: 126
lr:
  value: 0.000952476272291314
max_seq_len:
  value: 91
n_epochs:
  value: 60
n_layers:
  value: 1
optimizer:
  value: adamW
scheduler:
  value: linear_warmup
